spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false
  application:
    name: Payment Transaction Manager
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000
    virtual-host: /
    listener:
      simple:
        concurrency: 5   # Number of concurrent consumers
        max-concurrency: 10
        prefetch: 100    # Messages prefetch for consumer
jwt:
  secret: VxNr0zLCVMr71Wr0+GMy49yTTxaNKdkgvWVCmZve3RQ=
server:
  port: 8080