spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  application:
    name: Payment Transaction Manager
jwt:
  secret: VxNr0zLCVMr71Wr0+GMy49yTTxaNKdkgvWVCmZve3RQ=
server:
  port: 8080